spring.application.name=PicasYFijas
server.port=8080

# Configuración PostgreSQL en la nube (Render)
spring.datasource.url=jdbc:postgresql://dpg-d81tl6navr4c738bhvdg-a.oregon-postgres.render.com:5432/picasfijas_db
spring.datasource.username=picasfijas_db_user
spring.datasource.password=9sRt6Wjln8riZjrxfRYMqCUcXTE4HDmY

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false